# Generated by Django 5.2.4 on 2025-08-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinemate", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="created_at",
        ),
        migrations.AddField(
            model_name="movie",
            name="poster_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="tmdb_id",
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="release_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
