# Generated by Django 5.2.4 on 2025-08-29 10:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinemate", "0002_remove_movie_created_at_movie_poster_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="poster_url",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="tmdb_id",
        ),
        migrations.AddField(
            model_name="movie",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="movie",
            name="description",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="movie",
            name="release_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
