# Generated by Django 5.2.4 on 2025-08-29 12:34

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinemate", "0003_remove_movie_poster_url_remove_movie_tmdb_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="movie",
        ),
        migrations.AddField(
            model_name="review",
            name="movie_imdb_id",
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="movie",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="release_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ]
            ),
        ),
    ]
